### ISSUE TITLE
Track all modules created by Generamba

### ISSUE THREAD

**Issue by etolstoy** [rambler-digital-solutions/Generamba#70]
I've received a couple of feature requests for the command `generamba module list`, which would print out all of the modules, created in the current project by Generamba. This feature requires implementation of module tracking. 

This can be implemented by adding a special information file, generated alongside with a new module. This file (`.rambamodule`) may look like:

``` yml
module_name: BrandNewModule
template_name: rviper_controller
template_version: 1.0.3
```

So, when a user runs `generamba module list`, we can find all of this information files in the project dir, parse them and print out the module list.

Storing this kind of information allows us to implement other cool things - e.g. deleting/copying modules from command line.

@mogol @AndreyZarembo @Beniamiiin what are your thoughts?
